export { default as DashboardIcon } from './DashboardIcon';
export { default as DocumentIcon } from './DocumentIcon';
export { default as UsersIcon } from './UsersIcon';
export { default as BuildingIcon } from './BuildingIcon';
export { default as ChartIcon } from './ChartIcon';
export { default as SettingsIcon } from './SettingsIcon';
export { default as LogoutIcon } from './LogoutIcon';
export { default as MenuIcon } from './MenuIcon';
export { default as BellIcon } from './BellIcon';